# development:
#   :concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 1
:queues:
  - default

:verbose: false
:concurrency: 1
:timeout: 30

:schedule:
  EscalateTicketJob: 
    cron: '0 12 * * *' # Everyday at 12 pm 
    enabled: true
    active_job: true