# development:
#   :concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 1
:queues:
  - default

:verbose: false
:concurrency: 1
:timeout: 30

:schedule:
  EscalateTicketJob: 
    cron: '* * 12 * * *'
    enabled: true
    active_job: true